Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Mvc;
using VehicleDashboard.Models;

namespace VehicleDashboard.Controllers
{


    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _UploadFile(string VIN)
        {
            // "~/PDFs1550/"
            //var path = Server.MapPath(@"C:\inetpub\wwwroot\production\FITZWAY\Pictures\UCPDFS");
            var path = (@"C:\inetpub\wwwroot\production\FITZWAY\Pictures\UCPDFS");

            var dir = new DirectoryInfo(path);

        //    var files = dir.EnumerateFiles("????" + VIN + ".pdf").Select(f => f.Name);
            var files = dir.EnumerateFiles(VIN + ".pdf").Select(f => f.Name);
            ViewBag.UserMsg = VIN + ".pdf";
            ViewBag.UserWarn = "";
            if (files.Count() > 0)
            {
                ViewBag.UserWarn = "File Already There";
            }
            return View(files);
        }

        [HttpPost]
        public ActionResult _UploadFile(HttpPostedFileBase file)
        {
   
            if (file != null)
            {
                //   var path = Path.Combine(Server.MapPath(@"C:\inetpub\wwwroot\production\FITZWAY\Pictures\UCPDFS"), file.FileName);
                var path = Path.Combine((@"C:\inetpub\wwwroot\production\FITZWAY\Pictures\UCPDFS"), file.FileName);

                var data = new byte[file.ContentLength];
                file.InputStream.Read(data, 0, file.ContentLength);

                using (var sw = new FileStream(path, FileMode.Create))
                {
                    sw.Write(data, 0, data.Length);
                }
               
            }
            ViewBag.Processed = true;
            return View("");
        }
        public ActionResult yHandyman(string Location, string NoPDF)
        {
            var usedVehicleDashboard = new Models.UsedVehicleDashboard();

            if (Location == null)
            {
                Location = "ALL";
            }

            if (NoPDF == null)
            {
                NoPDF = "";
            }

            usedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            usedVehicleDashboard.AllUsedInventory = usedVehicleDashboard.AllUsedInventory.FindAll(x => (x.status == 1 || x.status == 2 || x.status == 4));

            usedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();
            usedVehicleDashboard.Location = Location;
            usedVehicleDashboard.VehicleData = Business.SqlQueries.GetAllChromedVehicles();
            usedVehicleDashboard.PDFs_1550_1551 = Business.SqlQueries.ALL_1551and1550_Files();
            usedVehicleDashboard.NoPDF = NoPDF;  // 1550, 1551, BOTH or blank if regular Handyman report

            return View(usedVehicleDashboard);
        }
        public ActionResult InRecon(string Location)
        {
            var usedVehicleDashboard = new Models.UsedVehicleDashboard();

            if (Location == null)
            {
                Location = "ALL";
            }

            usedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            usedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();
            usedVehicleDashboard.Location = Location;
            usedVehicleDashboard.VehicleData = Business.SqlQueries.GetAllChromedVehicles();


            return View(usedVehicleDashboard);
        }

        public ActionResult Handyman(string Location, string NoPDF, string DeleteFile)
        {
            var usedVehicleDashboard = new Models.UsedVehicleDashboard();

            if (Location == null)
            {
                Location = "ALL";
            }

            if (NoPDF == null)
            {
                NoPDF = "";
            }


            if (System.IO.File.Exists(DeleteFile))
            {
                System.IO.File.Delete(DeleteFile); // Delete the file
               // System.Threading.Thread.Sleep(4000);
            }

            usedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            usedVehicleDashboard.AllUsedInventory = usedVehicleDashboard.AllUsedInventory.FindAll(x => (x.status == 1 || x.status == 2 || x.status == 4));

            usedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();
            usedVehicleDashboard.Location = Location;
            usedVehicleDashboard.VehicleData = Business.SqlQueries.GetAllChromedVehicles();
            usedVehicleDashboard.PDFs_1550_1551 = Business.SqlQueries.ALL_1551and1550_Files();
            usedVehicleDashboard.NoPDF = NoPDF;  // 1550, 1551, BOTH or blank if regular Handyman report

            return View(usedVehicleDashboard);
        }



        public ActionResult NotCheckedOut(string Location)
        {
            var usedVehicleDashboard = new Models.UsedVehicleDashboard();

            if (Location == null)
            {
                Location = "ALL";
            }

            string UserCookie = Request.Cookies["user"].Value;
            ViewBag.UserRank = Business.SqlQueries.GetUserRole(UserCookie);

            usedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            usedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();
            usedVehicleDashboard.Location = Location;
            usedVehicleDashboard.VehicleData = Business.SqlQueries.GetAllChromedVehicles();
            usedVehicleDashboard.FitzwayCheckoutIDs = Business.SqlQueries.FitzWayCheckout_IDs();


            return View(usedVehicleDashboard);
        }

        public ActionResult FuelType(string Location, string Condition)
        {
            var vehicleOptionModel = new VehicleOptionModel();

            if (Location == null)
            {
                Location = "ALL";
            }

            if (Condition == null || Condition == "")
            {
                Condition = "ALL";
            }

            vehicleOptionModel.UsedVehicleDashboard = new UsedVehicleDashboard();
            vehicleOptionModel.UsedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            vehicleOptionModel.UsedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();

            vehicleOptionModel.NewVehicleDashboard = new NewVehicleDashboard();
            vehicleOptionModel.NewVehicleDashboard.AllNewInventory = Business.SqlQueries.GetAllNewInventory();
            vehicleOptionModel.NewVehicleDashboard.WebsiteNewInventory = Business.SqlQueries.GetWebsiteNewInventory();

            vehicleOptionModel.Location = Location;
            vehicleOptionModel.Condition = Condition;
            vehicleOptionModel.VehicleData = Business.SqlQueries.GetAllChromedVehicles();


            return View(vehicleOptionModel);
        }

        public ActionResult ManagerSpecials(string Location, string Condition)
        {
            var vehicleOptionModel = new VehicleOptionModel();

            if (Location == null || Location == "")
            {
                Location = "ALL";
            }

            if (Condition == null || Condition == "")
            {
                Condition = "ALL";
            }

            vehicleOptionModel.UsedVehicleDashboard = new UsedVehicleDashboard();
            vehicleOptionModel.UsedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            vehicleOptionModel.UsedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();

            vehicleOptionModel.NewVehicleDashboard = new NewVehicleDashboard();
            vehicleOptionModel.NewVehicleDashboard.AllNewInventory = Business.SqlQueries.GetAllNewInventory();
            vehicleOptionModel.NewVehicleDashboard.WebsiteNewInventory = Business.SqlQueries.GetWebsiteNewInventory();

            vehicleOptionModel.Location = Location;
            vehicleOptionModel.Condition = Condition;
            vehicleOptionModel.VehicleData = Business.SqlQueries.GetAllChromedVehicles();

            return View(vehicleOptionModel);
        }

        public ActionResult AllVehicles(string Location, string Condition, string PhotoShow)
        {
            var vehicleOptionModel = new VehicleOptionModel();

            if (Location == null || Location == "")
            {
                Location = "ALL";
            }

            if (Condition == null || Condition == "")
            {
                Condition = "ALL";
            }

            var mNewInventory = Business.SqlQueries.GetAllNewInventory();
            var mUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            var mNewWeb = Business.SqlQueries.GetWebsiteNewInventory();
            var mUsedWeb =  Business.SqlQueries.GetWebsiteUsedInventory();

            vehicleOptionModel.UsedVehicleDashboard = new UsedVehicleDashboard();
            vehicleOptionModel.NewVehicleDashboard = new NewVehicleDashboard();
            
            if (PhotoShow == null || PhotoShow =="") { 
                vehicleOptionModel.UsedVehicleDashboard.AllUsedInventory = mUsedInventory;
                vehicleOptionModel.UsedVehicleDashboard.WebsiteUsedInventory = mUsedWeb;
                vehicleOptionModel.NewVehicleDashboard.AllNewInventory = mNewInventory;
                vehicleOptionModel.NewVehicleDashboard.WebsiteNewInventory = mNewWeb;
            } else
            {
                switch (PhotoShow)
                { case "10P":
                        vehicleOptionModel.UsedVehicleDashboard.AllUsedInventory = mUsedInventory.FindAll(x=> x.Photos > 10);
                        vehicleOptionModel.UsedVehicleDashboard.WebsiteUsedInventory = mUsedWeb;

Views/Reports/FuelType.cshtml
@model VehicleDashboard.Models.VehicleOptionModel

@{
    ViewBag.Title = "Vehicles Missing Fuel Type";

    var applicationPath = Request.ApplicationPath;

    if (applicationPath == "/")
    {
        applicationPath = "";
    }

    System.Globalization.NumberFormatInfo nfi = new System.Globalization.CultureInfo("en-US", false).NumberFormat;
    nfi.CurrencyDecimalDigits = 0;
    nfi.PercentDecimalDigits = 1;
    nfi.CurrencySymbol = "";

    var locations = Model.UsedVehicleDashboard.WebsiteUsedInventory.Select(x => x.V_loc).Distinct().OrderBy(X => X).ToList();

    var missingFuelType = Model.VehicleData.FindAll(x => x.FuelType == null);

    if (Model.Location != null && Model.Location != "ALL")
    {
        if (Model.Location == "FBC")
        {
            missingFuelType = missingFuelType.FindAll(x => (x.VehicleLocation == "FBS" || x.VehicleLocation == "FBC"));
        }
        else
        {
            missingFuelType = missingFuelType.FindAll(x => x.VehicleLocation == Model.Location);
        }
    }

    if (Model.Condition != null && Model.Condition.ToUpper() == "USED")
    {
        missingFuelType = missingFuelType.FindAll(x => x.Condition == "USED");
    }
    else if (Model.Condition != null && Model.Condition.ToUpper() == "NEW")
    {
        missingFuelType = missingFuelType.FindAll(x => x.Condition == "NEW");
    }

}

@section CSS
{
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    <style type="text/css">
        .location-row {
            background-color: #eee;
        }
    </style>
}

<div class="row" style="border-bottom:1px solid #eee; margin-bottom:20px;">
    <div class="col-sm-12 col-md-10">
        <h2>Vehicles Missing Fuel Type</h2>
        <div class="row location-row">
            <div class="col-xs-12">
                <h4>Locations:</h4>
                <input class="form-inline" type="radio" name="locationValue" id="chk-ALL" onclick="window.location='@applicationPath/Reports/FuelType?Location=ALL&Condition=@Model.Condition';" value="ALL" @(Model.Location == "ALL" ? "checked" : "" )>
                <label class="form-inline" style="margin-right:15px;" for="chk-ALL">ALL</label>

                @foreach (var location in locations)
                {
                    <input class="form-inline" type="radio" name="locationValue" id="chk-@location" onclick="window.location='@applicationPath/Reports/FuelType?Location=@location&Condition=@Model.Condition';" value="@location" @(Model.Location == location ? "checked" : "" )>
                    <label class="form-inline" style="margin-right:15px;" for="chk-@location">@location</label>
                }
            </div>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12">
        <table class="table table-striped table-bordered" id="table-InRecon">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Stock #</th>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Days</th>
                    <th>List Amt</th>
                    <th>Status</th>
                    <th>Style Id</th>
                    <th>Fuel Type</th>
                    <th>Manager Special</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var vehicle in missingFuelType)
                {
                    var vehicleDetails = new VehicleDashboard.Models.CSV_vehicleUSED();
                    if (Model.Condition != null && Model.Condition.ToUpper() == "USED")
                    {
                        vehicleDetails = Model.UsedVehicleDashboard.AllUsedInventory.Find(x => x.vin == vehicle.VIN);
                        if (vehicleDetails.status == 1 || vehicleDetails.status == 2 || vehicleDetails.status == 4)
                        {

                            <tr>
                                <td>@vehicle.VehicleLocation</td>

                                @if (vehicle.StyleId > 0)
                                {
                                    <td><a href="@applicationPath/Chrome/Vehicle/?VIN=@vehicle.VIN&Chromed=true" target="_blank">@vehicle.StockNumber</a></td>
                                }
                                else if (vehicle.StyleId == 0)
                                {
                                    <td><a href="@applicationPath/Chrome/ChromeNoStyle/?VIN=@vehicle.VIN" target="_blank">@vehicle.StockNumber</a></td>
                                }

                                <td>@vehicle.Year</td>
                                <td>@vehicle.Make</td>
                                <td>@vehicle.Model</td>
                                <td>@vehicleDetails.daysinv</td>
                                <td>@vehicleDetails.list_amt.ToString("C", nfi)</td>
                                <td>@vehicleDetails.status</td>
                                <td>@vehicle.StyleId</td>
                                <td>@vehicle.FuelType</td>
                                @if (vehicle.ManagerSpecial > 0)
                                {
                                    <td>YES</td>
                                }
                                else
                                {
                                    <td> </td>
                                }
                            </tr>

                        }
                    }
                    else
                    {
                        var details = Model.NewVehicleDashboard.AllNewInventory.Find(x => x.vin == vehicle.VIN);
                        if (details != null)
                        {

                            vehicleDetails.daysinv = Int32.Parse(details.days);
                            vehicleDetails.list_amt = details.list_amt;
                            vehicleDetails.status = details.status;

                            if (details.status != 26 || details.status != 7)
                            {

                                <tr>
                                    <td>@vehicle.VehicleLocation</td>

                                    @if (vehicle.StyleId > 0)
                                    {
                                        <td><a href="@applicationPath/Chrome/Vehicle/?VIN=@vehicle.VIN&Chromed=true" target="_blank">@vehicle.StockNumber</a></td>
                                    }
                                    else if (vehicle.StyleId == 0)
                                    {
                                        <td><a href="@applicationPath/Chrome/ChromeNoStyle/?VIN=@vehicle.VIN" target="_blank">@vehicle.StockNumber</a></td>
                                    }

                                    <td>@vehicle.Year</td>
                                    <td>@vehicle.Make</td>
                                    <td>@vehicle.Model</td>
                                    <td>@vehicleDetails.daysinv</td>
                                    <td>@vehicleDetails.list_amt.ToString("C", nfi)</td>
                                    <td>@vehicleDetails.status</td>
                                    <td>@vehicle.StyleId</td>
                                    <td>@vehicle.FuelType</td>
                                    @if (vehicle.ManagerSpecial > 0)
                                    {
                                        <td>YES</td>
                                    }
                                    else
                                    {
                                        <td> </td>
                                    }
                                </tr>
                            }

                        }


                    }
                }



            </tbody>
        </table>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table-InRecon').DataTable({
                searching: true,
                dom: 'Bfrti',
                pageLength: -1,
                buttons: [
                    {
                        extend: 'copyHtml5', footer: true,
                    },
                    {
                        extend: 'excelHtml5', footer: true,
                    },
                    {
                        extend: 'pdfHtml5', footer: true,
                        orientation: 'landscape'
                    },
                    {
                        extend: 'print', footer: true,
                        orientation: 'landscape'
                    }
                ]
                //,
                //columnDefs: [
                //  { type: 'any-number', targets: [18, 19, 20, 21, 22, 23, 24,25,26] },
                //  { type: 'date-us', targets: [6] }
                //]

            });

        });

    </script>
}

Views/Reports/Handyman.cshtml
@model VehicleDashboard.Models.UsedVehicleDashboard

@{
    ViewBag.Title = "Handyman";

    var applicationPath = Request.ApplicationPath;
    var PDFpath = (@"C:\\inetpub\\wwwroot\\production\\FITZWAY\\Pictures\\UCPDFS");
    var dir = new DirectoryInfo(PDFpath);
    var files = dir.EnumerateFiles("*.pdf").Select(f => f.Name);
    var findFile = "";
    var functionCall = "";

    if (applicationPath == "/")
    {
        applicationPath = "";
    }

    System.Globalization.NumberFormatInfo nfi = new System.Globalization.CultureInfo("en-US", false).NumberFormat;
    nfi.CurrencyDecimalDigits = 0;
    nfi.PercentDecimalDigits = 1;
    nfi.CurrencySymbol = "";

    var locations = Model.WebsiteUsedInventory.Select(x => x.V_loc).Distinct().OrderBy(X => X).ToList();
    string UploadVIN = "";

    var HandymanVehicles = Model.AllUsedInventory.FindAll(x => x.slscode == "HDM");

    if (Model.Location != null && Model.Location != "ALL")
    {
        if (Model.Location == "FBC")
        {
            HandymanVehicles = HandymanVehicles.FindAll(x => (x.loc == "FBS" || x.loc == "FBC") && x.slscode == "HDM");
        }
        else
        {
            HandymanVehicles = HandymanVehicles.FindAll(x => x.loc == Model.Location && x.slscode == "HDM");
        }
    }

    if (Model.NoPDF == "1550")
    {
        ViewBag.Title = "Handyman Missing 1550 Form";
    }

    if (Model.NoPDF == "1551")
    {
        ViewBag.Title = "Handyman Missing 1551 Form";
    }

    if (Model.NoPDF == "BOTH")
    {
        ViewBag.Title = "Handyman Missing BOTH 1550 and 1551 Forms";
    }
}

@section CSS
{
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    <style type="text/css">
        .location-row {
            background-color: #eee;
        }
    </style>
}

<div class="row" style="border-bottom:1px solid #eee; margin-bottom:20px;">
    <div class="col-sm-12 col-md-10">
        <h2>@ViewBag.Title</h2>
        <div class="row location-row">
            <div class="col-xs-12">
                <h4>Locations:</h4>
                <input class="form-inline" type="radio" name="locationValue" id="chk-ALL" onclick="window.location='@applicationPath/Reports/InRecon?Location=ALL';" value="ALL" @(Model.Location == "ALL" ? "checked" : "" )>
                <label class="form-inline" style="margin-right:15px;" for="chk-ALL">ALL</label>

                @foreach (var location in locations)
                {
                    <input class="form-inline" type="radio" name="locationValue" id="chk-@location" onclick="window.location='@applicationPath/Reports/InRecon?Location=@location';" value="@location" @(Model.Location == location ? "checked" : "" )>
                    <label class="form-inline" style="margin-right:15px;" for="chk-@location">@location</label>
                }
            </div>

        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12 col-md-12">
        <table class="table table-striped table-bordered" id="table-InRecon">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Stock #</th>
                    <th>Year</th>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Days</th>
                    <th>List Amt</th>
                    <th>Status</th>
                    @if (Model.NoPDF == "")
                    {
                        <th></th>
                        <th></th>
                    }
                    else
                    {
                        <th></th>
                    }

                </tr>
            </thead>
            <tbody>
                @if (Model.NoPDF == "")
                {
                    foreach (var vehicle in HandymanVehicles)
                    {
                        var vehicleDetails = Model.AllUsedInventory.Find(x => x.vin == vehicle.vin);

                        UploadVIN = vehicle.vin;

                        if (vehicleDetails.slscode == "HDM")
                        {
                            <tr>
                                <td>@vehicle.loc</td>

                                <td><a href="https://responsive.fitzmall.com/Inventory/Detail/@vehicle.vin" target="_blank">@vehicle.stk</a></td>
                                <td>@vehicle.yr</td>
                                <td>@vehicle.make</td>
                                <td>@vehicle.carline</td>
                                <td>@vehicleDetails.daysinv</td>
                                <td>@vehicleDetails.list_amt.ToString("C", nfi)</td>
                                <td>@vehicleDetails.status</td>
                                @if (UploadVIN != "")
                                {
                                    findFile = PDFpath + @"\\101-" + UploadVIN + ".pdf";
                                    functionCall = "deleteFile(" + findFile + ")";
                                    if (System.IO.File.Exists(findFile))
                                    {
                                        <td>
                                            <button id="@findFile" value="@findFile" onclick="deleteFile1550('@findFile')">Delete 1550 Form</button>
                                        </td>
                                    }
                                    else
                                    {
                                        <td></td>
                                    }

                                    findFile = PDFpath + @"\\151-" + UploadVIN + ".pdf";
                                    if (System.IO.File.Exists(findFile))
                                    {
                                        <td>
                                            <button id="@findFile" value="@findFile" onclick="deleteFile1551('@findFile')">Delete 1551 Form</button>
                                        </td>
                                    }
                                    else
                                    {
                                        <td></td>
                                    }


                                }
                                else
                                {
                                    <td></td>
                                    <td></td>
                                }


                            </tr>
                        }
                    }
                }

                @if (Model.NoPDF == "1550")
                {
                    foreach (var vehicle in HandymanVehicles)
                    {
                        var vehicleDetails = Model.AllUsedInventory.Find(x => x.vin == vehicle.vin);
                        if (vehicleDetails.slscode == "HDM")
                        {


                            if ((Model.PDFs_1550_1551.Count(x => x.VIN == vehicle.vin && x.Counter1550 > 0)) == 0)
                            {
                                UploadVIN = "101-" + vehicle.vin;

                                <tr>
                                    <td>@vehicle.loc</td>

                                    <td><a href="https://responsive.fitzmall.com/Inventory/Detail/@vehicle.vin" target="_blank">@vehicle.stk</a></td>
                                    <td>@vehicle.stk</td>
                                    <td>@vehicle.yr</td>
                                    <td>@vehicle.make</td>
                                    <td>@vehicle.carline</td>
                                    <td>@vehicleDetails.daysinv</td>
                                    <td>@vehicleDetails.list_amt.ToString("C", nfi)</td>
                                    <td>@vehicleDetails.status</td>
                                    <td><a href="@applicationPath/Reports/_UploadFile?VIN=@UploadVIN" target="_blank">UPLOAD</a></td>
                                </tr>
                            }
                        }
                    }
                }
                @if (Model.NoPDF == "1551")
                {
                    foreach (var vehicle in HandymanVehicles)
                    {
                        var vehicleDetails = Model.AllUsedInventory.Find(x => x.vin == vehicle.vin);
                        if (vehicleDetails.slscode == "HDM")
                        {
                            if ((Model.PDFs_1550_1551.Count(x => x.VIN == vehicle.vin && x.Counter1551 > 0)) == 0)
                            {
                                UploadVIN = "151-" + vehicle.vin;
                                {
                                    <tr>
                                        <td>@vehicle.loc</td>

                                        <td><a href="https://responsive.fitzmall.com/Inventory/Detail/@vehicle.vin" target="_blank">@vehicle.stk</a></td>
                                        <td>@vehicle.yr</td>
                                        <td>@vehicle.make</td>
                                        <td>@vehicle.carline</td>
                                        <td>@vehicleDetails.daysinv</td>
                                        <td>@vehicleDetails.list_amt.ToString("C", nfi)</td>
                                        <td>@vehicleDetails.status</td>
                                        <td><a href="@applicationPath/Reports/_UploadFile?VIN=@UploadVIN" target="_blank">UPLOAD</a></td>

                                    </tr>
                                }
                            }
                        }
                    }
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#table-InRecon').DataTable({
                searching: true,
                dom: 'Bfrti',
                pageLength: -1,
                buttons: [
                    {
                        extend: 'copyHtml5', footer: true,
                    },
                    {
                        extend: 'excelHtml5', footer: true,
                    },
                    {
                        extend: 'pdfHtml5', footer: true,
                        orientation: 'landscape'
                    },
                    {
                        extend: 'print', footer: true,
                        orientation: 'landscape'
                    }
                ]
                //,
                //columnDefs: [
                //  { type: 'any-number', targets: [18, 19, 20, 21, 22, 23, 24,25,26] },
                //  { type: 'date-us', targets: [6] }
                //]

            });

        });

        function getFileName(path) {
            return path.match(/[-_\w]+[.][\w]+$/i)[0];
        }

        function deleteFile1550(param) {

            var button = document.getElementById(param);
            var shortName = getFileName(param)

            var r = confirm("Are you sure you want to delete " + shortName + "?");
            if (r) {
                $.ajax({
                    url: '/Reports/Handyman',
                    data: { 'DeleteFile': param },
                    type: 'post',
                    success: function (response) {
                        // Handle success (e.g., show a message)
                        location.reload();
                        console.log("success " + param);

                    },
                    error: function () {
                        // Handle error (e.g., display an error message)
                        console.log("fail " + param);

                    }
                });
            }
        }

        function deleteFile1551(param) {

            var shortName = getFileName(param)

            var r = confirm("Are you sure you want to delete " + shortName + "?");
            if (r) {
                $.ajax({
                    url: '/Reports/Handyman',
                    data: { 'DeleteFile': param },
                    type: 'post',
                    success: function (response) {
                        // Handle success (e.g., show a message)
                        location.reload();
                    },
                    error: function () {
                        // Handle error (e.g., display an error message)
                    }
                });
            }
        }

    </script>
}

Views/Reports/_UploadFile.cshtml
@model IEnumerable<string>
<link rel="stylesheet" href="~\Content\Site.css">
<h1>Upload </h1>
<h3>Upload this filename:  @ViewBag.UserMsg</h3>
<h2>@ViewBag.UserWarn</h2>

<div>
    @using (Html.BeginForm("_UploadFile", "Reports", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="File" name="file" id="file" value="Choose File" accept=".pdf" />
        <br>
        <br>
        <button type="submit">Upload</button>
    }
</div>

@if (null != ViewBag.Processed && (bool)ViewBag.Processed == true)
{
    <script>
        window.close();
    </script>
}