Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VehicleDashboard.Controllers
{
    public class NewController : Controller
    {
        // GET: New
        public ActionResult Index(string Location)
        {
            var newVehicleDashboard = new Models.NewVehicleDashboard();

            if (Location == null)
            {
                Location = "ALL";
            }

            newVehicleDashboard.AllNewInventory = Business.SqlQueries.GetAllNewInventory();
            newVehicleDashboard.WebsiteNewInventory = Business.SqlQueries.GetWebsiteNewInventory();
            newVehicleDashboard.Location = Location;
            newVehicleDashboard.Photos = Business.SqlQueries.GetPhotoNumberByVIN_NEW();

            return View(newVehicleDashboard);
        }
    }
}

Controllers/UsedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VehicleDashboard.Controllers
{
    public class UsedController : Controller
    {
        // GET: Used
        public ActionResult Index(string Location)
        {
            var usedVehicleDashboard = new Models.UsedVehicleDashboard();

            if(Location == null)
            {
                Location = "ALL";
            }

            usedVehicleDashboard.AllUsedInventory = Business.SqlQueries.GetAllUsedInventory();
            usedVehicleDashboard.WebsiteUsedInventory = Business.SqlQueries.GetWebsiteUsedInventory();
            usedVehicleDashboard.Location = Location;
            usedVehicleDashboard.Photos = Business.SqlQueries.GetPhotoNumberByVIN_USED();

            return View(usedVehicleDashboard);
        }
    }
}

Views/Shared/_Layout.cshtml
@{


}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitzgerald Vehicle Dashboard</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/vehicledashboard.css" rel="stylesheet" />

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-flash-1.5.1/b-html5-1.5.1/b-print-1.5.1/datatables.min.css" />

    @RenderSection("CSS", required: false)

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/dt-1.10.16/b-1.5.1/b-flash-1.5.1/b-html5-1.5.1/b-print-1.5.1/datatables.min.js"></script>

    <style>
        .dropdown-submenu {
            position: relative;
        }

            .dropdown-submenu > .dropdown-menu {
                top: 0;
                left: 100%;
                margin-top: -6px;
                margin-left: -1px;
                -webkit-border-radius: 0 4px 4px 4px;
                -moz-border-radius: 0 4px 4px 4px;
                border-radius: 0 4px 4px 4px;
            }

            .dropdown-submenu:hover > .dropdown-menu {
                display: block;
            }

            .dropdown-submenu > a:after {
                display: block;
                content: " ";
                float: right;
                width: 0;
                height: 0;
                border-color: transparent;
                border-style: solid;
                border-width: 5px 0 5px 5px;
                border-left-color: #cccccc;
                margin-top: 5px;
                margin-right: -10px;
            }

            .dropdown-submenu:hover > a:after {
                border-left-color: #ffffff;
            }

            .dropdown-submenu.pull-left {
                float: none;
            }

                .dropdown-submenu.pull-left > .dropdown-menu {
                    left: -100%;
                    margin-left: 10px;
                    -webkit-border-radius: 4px 0 4px 4px;
                    -moz-border-radius: 4px 0 4px 4px;
                    border-radius: 4px 0 4px 4px;
                }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="http://JJFServer/" class="navbar-brand"><i class="fa fa-home" aria-hidden="true"></i> JJFServer</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Vehicles", "Index", "New")</li> 
                    <li>@Html.ActionLink("Used Vehicles", "Index", "Used")</li>
                    <li>@Html.ActionLink("Vehicle Options", "Index", "Chrome")</li>                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Reporting
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/Reporting/InventorySummary">Inventory Summary</a></li>
                            <li><a href="/Reporting/InventoryManagement">Inventory Management</a></li>
                            <li><a href="/Reporting/ReconPricing">Reconditioning/Pricing</a></li>
                            <li><a href="/Reporting/Chrome">Chrome</a></li>
                            <li><a href="/Reporting/Pictures">Pictures</a></li>
                            <li><a href="/Reporting/Pictures">NextCar</a></li>
                            <li><a href="/Reporting/Sales">Sales</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fitzgerald Auto Malls</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")

    <script type="text/javascript">
        _anyNumberSort = function (a, b, high) {
            var reg = /[+-]?((\d+(\.\d*)?)|\.\d+)([eE][+-]?[0-9]+)?/;

            if (a.match(/[\()]/g)) {
                if (a.match(/[\-]/g) !== true) {
                    //It matched - strip out parentheses & any characters we dont want and append - at front
                    a = '-' + a.replace(/[\$£€c\(\),]/g, '');
                }
            }
            if (b.match(/[\()]/g)) {
                if (b.match(/[\-]/g) !== true) {
                    //It matched - strip out parentheses & any characters we dont want and append - at front
                    b = '-' + b.replace(/[\$£€c\(\),]/g, '');
                }
            }

            a = a.replace(/[\$£€\,]/g, '');
            b = b.replace(/[\$£€\,]/g, '');

            a = a.replace(',', '.').match(reg);
            a = a !== null ? parseFloat(a[0]) : high;
            b = b.replace(',', '.').match(reg);
            b = b !== null ? parseFloat(b[0]) : high;
            return ((a < b) ? -1 : ((a > b) ? 1 : 0));
        }

        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "any-number-asc": function (a, b) {
                return _anyNumberSort(a, b, Number.POSITIVE_INFINITY);
            },
            "any-number-desc": function (a, b) {
                return _anyNumberSort(a, b, Number.NEGATIVE_INFINITY) * -1;
            }
        });

        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "date-us-pre": function (a) {
                if (a == null || a == "") {
                    return 0;
                }
                var usDatea = a.split('/');
                return (usDatea[2] + usDatea[1] + usDatea[0]) * 1;
            },

            "date-us-asc": function (a, b) {
                return ((a < b) ? -1 : ((a > b) ? 1 : 0));
            },

            "date-us-desc": function (a, b) {
                return ((a < b) ? 1 : ((a > b) ? -1 : 0));
            }
        });
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>